export const ALLAH_NAMES = [
  { id: 1, arabic: "الرَّحْمَٰنُ", transliteration: "Ar-Rahman", translation: "The Most Merciful" },
  { id: 2, arabic: "الرَّحِيمُ", transliteration: "Ar-Rahim", translation: "The Especially Merciful" },
  { id: 3, arabic: "الْمَلِكُ", transliteration: "Al-Malik", translation: "The King" },
  { id: 4, arabic: "الْقُدُّوسُ", transliteration: "Al-Quddus", translation: "The Absolutely Pure" },
  { id: 5, arabic: "السَّلَامُ", transliteration: "As-Salam", translation: "The Giver of Peace" },
  { id: 6, arabic: "الْمُؤْمِنُ", transliteration: "Al-Mu'min", translation: "The Granter of Security" },
  { id: 7, arabic: "الْمُهَيْمِنُ", transliteration: "Al-Muhaymin", translation: "The Guardian" },
  { id: 8, arabic: "الْعَزِيزُ", transliteration: "Al-Aziz", translation: "The Almighty" },
  { id: 9, arabic: "الْجَبَّارُ", transliteration: "Al-Jabbar", translation: "The Compeller" },
  { id: 10, arabic: "الْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", translation: "The Supreme" },
  { id: 11, arabic: "الْخَالِقُ", transliteration: "Al-Khaliq", translation: "The Creator" },
  { id: 12, arabic: "الْبَارِئُ", transliteration: "Al-Bari", translation: "The Originator" },
  { id: 13, arabic: "الْمُصَوِّرُ", transliteration: "Al-Musawwir", translation: "The Fashioner" },
  { id: 14, arabic: "الْغَفَّارُ", transliteration: "Al-Ghaffar", translation: "The Constant Forgiver" },
  { id: 15, arabic: "الْقَهَّارُ", transliteration: "Al-Qahhar", translation: "The Subduer" },
  { id: 16, arabic: "الْوَهَّابُ", transliteration: "Al-Wahhab", translation: "The Bestower" },
  { id: 17, arabic: "الرَّزَّاقُ", transliteration: "Ar-Razzaq", translation: "The Provider" },
  { id: 18, arabic: "الْفَتَّاحُ", transliteration: "Al-Fattah", translation: "The Opener" },
  { id: 19, arabic: "الْعَلِيمُ", transliteration: "Al-Alim", translation: "The All-Knowing" },
  { id: 20, arabic: "الْقَابِضُ", transliteration: "Al-Qabid", translation: "The Withholder" },
  { id: 21, arabic: "الْبَاسِطُ", transliteration: "Al-Basit", translation: "The Extender" },
  { id: 22, arabic: "الْخَافِضُ", transliteration: "Al-Khafid", translation: "The Reducer" },
  { id: 23, arabic: "الرَّافِعُ", transliteration: "Ar-Rafi", translation: "The Exalter" },
  { id: 24, arabic: "الْمُعِزُّ", transliteration: "Al-Mu'izz", translation: "The Honourer" },
  { id: 25, arabic: "الْمُذِلُّ", transliteration: "Al-Mudhill", translation: "The Dishonourer" },
  { id: 26, arabic: "السَّمِيعُ", transliteration: "As-Sami", translation: "The All-Hearing" },
  { id: 27, arabic: "الْبَصِيرُ", transliteration: "Al-Basir", translation: "The All-Seeing" },
  { id: 28, arabic: "الْحَكَمُ", transliteration: "Al-Hakam", translation: "The Judge" },
  { id: 29, arabic: "الْعَدْلُ", transliteration: "Al-Adl", translation: "The Utterly Just" },
  { id: 30, arabic: "اللَّطِيفُ", transliteration: "Al-Latif", translation: "The Gentle" },
  { id: 31, arabic: "الْخَبِيرُ", transliteration: "Al-Khabir", translation: "The All-Aware" },
  { id: 32, arabic: "الْحَلِيمُ", transliteration: "Al-Halim", translation: "The Forbearing" },
  { id: 33, arabic: "الْعَظِيمُ", transliteration: "Al-Azim", translation: "The Magnificent" },
  { id: 34, arabic: "الْغَفُورُ", transliteration: "Al-Ghafur", translation: "The Forgiving" },
  { id: 35, arabic: "الشَّكُورُ", transliteration: "Ash-Shakur", translation: "The Appreciative" },
  { id: 36, arabic: "الْعَلِيُّ", transliteration: "Al-Ali", translation: "The Most High" },
  { id: 37, arabic: "الْكَبِيرُ", transliteration: "Al-Kabir", translation: "The Greatest" },
  { id: 38, arabic: "الْحَفِيظُ", transliteration: "Al-Hafiz", translation: "The Preserver" },
  { id: 39, arabic: "الْمُقِيتُ", transliteration: "Al-Muqit", translation: "The Sustainer" },
  { id: 40, arabic: "الْحَسِيبُ", transliteration: "Al-Hasib", translation: "The Reckoner" },
  { id: 41, arabic: "الْجَلِيلُ", transliteration: "Al-Jalil", translation: "The Majestic" },
  { id: 42, arabic: "الْكَرِيمُ", transliteration: "Al-Karim", translation: "The Most Generous" },
  { id: 43, arabic: "الرَّقِيبُ", transliteration: "Ar-Raqib", translation: "The Watchful" },
  { id: 44, arabic: "الْمُجِيبُ", transliteration: "Al-Mujib", translation: "The Responsive" },
  { id: 45, arabic: "الْوَاسِعُ", transliteration: "Al-Wasi", translation: "The All-Encompassing" },
  { id: 46, arabic: "الْحَكِيمُ", transliteration: "Al-Hakim", translation: "The All-Wise" },
  { id: 47, arabic: "الْوَدُودُ", transliteration: "Al-Wadud", translation: "The Most Loving" },
  { id: 48, arabic: "الْمَجِيدُ", transliteration: "Al-Majid", translation: "The Glorious" },
  { id: 49, arabic: "الْبَاعِثُ", transliteration: "Al-Ba'ith", translation: "The Resurrector" },
  { id: 50, arabic: "الشَّهِيدُ", transliteration: "Ash-Shahid", translation: "The All-Witnessing" },
  { id: 51, arabic: "الْحَقُّ", transliteration: "Al-Haqq", translation: "The Absolute Truth" },
  { id: 52, arabic: "الْوَكِيلُ", transliteration: "Al-Wakil", translation: "The Trustee" },
  { id: 53, arabic: "الْقَوِيُّ", transliteration: "Al-Qawiyy", translation: "The All-Strong" },
  { id: 54, arabic: "الْمَتِينُ", transliteration: "Al-Matin", translation: "The Firm" },
  { id: 55, arabic: "الْوَلِيُّ", transliteration: "Al-Waliyy", translation: "The Protector" },
  { id: 56, arabic: "الْحَمِيدُ", transliteration: "Al-Hamid", translation: "The Praiseworthy" },
  { id: 57, arabic: "الْمُحْصِي", transliteration: "Al-Muhsi", translation: "The Appraiser" },
  { id: 58, arabic: "الْمُبْدِئُ", transliteration: "Al-Mubdi", translation: "The Originator" },
  { id: 59, arabic: "الْمُعِيدُ", transliteration: "Al-Mu'id", translation: "The Restorer" },
  { id: 60, arabic: "الْمُحْيِي", transliteration: "Al-Muhyi", translation: "The Giver of Life" },
  { id: 61, arabic: "الْمُمِيتُ", transliteration: "Al-Mumit", translation: "The Creator of Death" },
  { id: 62, arabic: "الْحَيُّ", transliteration: "Al-Hayy", translation: "The Ever-Living" },
  { id: 63, arabic: "الْقَيُّومُ", transliteration: "Al-Qayyum", translation: "The Sustainer" },
  { id: 64, arabic: "الْوَاجِدُ", transliteration: "Al-Wajid", translation: "The Finder" },
  { id: 65, arabic: "الْمَاجِدُ", transliteration: "Al-Majid", translation: "The Illustrious" },
  { id: 66, arabic: "الْوَاحِدُ", transliteration: "Al-Wahid", translation: "The One" },
  { id: 67, arabic: "الْأَحَدُ", transliteration: "Al-Ahad", translation: "The Unique" },
  { id: 68, arabic: "الصَّمَدُ", transliteration: "As-Samad", translation: "The Eternal" },
  { id: 69, arabic: "الْقَادِرُ", transliteration: "Al-Qadir", translation: "The Able" },
  { id: 70, arabic: "الْمُقْتَدِرُ", transliteration: "Al-Muqtadir", translation: "The Powerful" },
  { id: 71, arabic: "الْمُقَدِّمُ", transliteration: "Al-Muqaddim", translation: "The Expediter" },
  { id: 72, arabic: "الْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", translation: "The Delayer" },
  { id: 73, arabic: "الْأَوَّلُ", transliteration: "Al-Awwal", translation: "The First" },
  { id: 74, arabic: "الْآخِرُ", transliteration: "Al-Akhir", translation: "The Last" },
  { id: 75, arabic: "الظَّاهِرُ", transliteration: "Az-Zahir", translation: "The Manifest" },
  { id: 76, arabic: "الْبَاطِنُ", transliteration: "Al-Batin", translation: "The Hidden" },
  { id: 77, arabic: "الْوَالِي", transliteration: "Al-Wali", translation: "The Governor" },
  { id: 78, arabic: "الْمُتَعَالِي", transliteration: "Al-Muta'ali", translation: "The Self-Exalted" },
  { id: 79, arabic: "الْبَرُّ", transliteration: "Al-Barr", translation: "The Source of Goodness" },
  { id: 80, arabic: "التَّوَّابُ", transliteration: "At-Tawwab", translation: "The Ever-Pardoning" },
  { id: 81, arabic: "الْمُنْتَقِمُ", transliteration: "Al-Muntaqim", translation: "The Avenger" },
  { id: 82, arabic: "الْعَفُوُّ", transliteration: "Al-Afuww", translation: "The Pardoner" },
  { id: 83, arabic: "الرَّؤُوفُ", transliteration: "Ar-Ra'uf", translation: "The Most Kind" },
  { id: 84, arabic: "مَالِكُ الْمُلْكِ", transliteration: "Malik-ul-Mulk", translation: "Owner of the Kingdom" },
  { id: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "Dhu-l-Jalali wa-l-Ikram", translation: "Lord of Majesty and Bounty" },
  { id: 86, arabic: "الْمُقْسِطُ", transliteration: "Al-Muqsit", translation: "The Just One" },
  { id: 87, arabic: "الْجَامِعُ", transliteration: "Al-Jami", translation: "The Gatherer" },
  { id: 88, arabic: "الْغَنِيُّ", transliteration: "Al-Ghaniyy", translation: "The Self-Sufficient" },
  { id: 89, arabic: "الْمُغْنِيُّ", transliteration: "Al-Mughni", translation: "The Enricher" },
  { id: 90, arabic: "الْمَانِعُ", transliteration: "Al-Mani", translation: "The Withholder" },
  { id: 91, arabic: "الضَّارُّ", transliteration: "Ad-Darr", translation: "The Distresser" },
  { id: 92, arabic: "النَّافِعُ", transliteration: "An-Nafi", translation: "The Benefactor" },
  { id: 93, arabic: "النُّورُ", transliteration: "An-Nur", translation: "The Light" },
  { id: 94, arabic: "الْهَادِي", transliteration: "Al-Hadi", translation: "The Guide" },
  { id: 95, arabic: "الْبَدِيعُ", transliteration: "Al-Badi", translation: "The Incomparable" },
  { id: 96, arabic: "الْبَاقِي", transliteration: "Al-Baqi", translation: "The Ever-Lasting" },
  { id: 97, arabic: "الْوَارِثُ", transliteration: "Al-Warith", translation: "The Inheritor" },
  { id: 98, arabic: "الرَّشِيدُ", transliteration: "Ar-Rashid", translation: "The Guide" },
  { id: 99, arabic: "الصَّبُورُ", transliteration: "As-Sabur", translation: "The Patient" }
];